// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hellostream.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba4696d1406ab37a, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba4696d1406ab37a, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// +
type ClientStream struct {
	Stream               []byte   `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientStream) Reset()         { *m = ClientStream{} }
func (m *ClientStream) String() string { return proto.CompactTextString(m) }
func (*ClientStream) ProtoMessage()    {}
func (*ClientStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba4696d1406ab37a, []int{2}
}

func (m *ClientStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientStream.Unmarshal(m, b)
}
func (m *ClientStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientStream.Marshal(b, m, deterministic)
}
func (m *ClientStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientStream.Merge(m, src)
}
func (m *ClientStream) XXX_Size() int {
	return xxx_messageInfo_ClientStream.Size(m)
}
func (m *ClientStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientStream.DiscardUnknown(m)
}

var xxx_messageInfo_ClientStream proto.InternalMessageInfo

func (m *ClientStream) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

type ServerStream struct {
	Stream               []byte   `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStream) Reset()         { *m = ServerStream{} }
func (m *ServerStream) String() string { return proto.CompactTextString(m) }
func (*ServerStream) ProtoMessage()    {}
func (*ServerStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba4696d1406ab37a, []int{3}
}

func (m *ServerStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStream.Unmarshal(m, b)
}
func (m *ServerStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStream.Marshal(b, m, deterministic)
}
func (m *ServerStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStream.Merge(m, src)
}
func (m *ServerStream) XXX_Size() int {
	return xxx_messageInfo_ServerStream.Size(m)
}
func (m *ServerStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStream.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStream proto.InternalMessageInfo

func (m *ServerStream) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "pb.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "pb.HelloResponse")
	proto.RegisterType((*ClientStream)(nil), "pb.ClientStream")
	proto.RegisterType((*ServerStream)(nil), "pb.ServerStream")
}

func init() { proto.RegisterFile("hellostream.proto", fileDescriptor_ba4696d1406ab37a) }

var fileDescriptor_ba4696d1406ab37a = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x6a, 0x84, 0x30,
	0x14, 0x45, 0x4d, 0x29, 0xd6, 0x3e, 0x2c, 0xd4, 0x2c, 0x8a, 0xb8, 0x2a, 0x59, 0x14, 0xdb, 0x85,
	0xd8, 0xf6, 0x13, 0xdc, 0xcc, 0x5a, 0xbf, 0x20, 0x0e, 0x8f, 0x51, 0x50, 0x93, 0xc9, 0x8b, 0x03,
	0xf3, 0xf7, 0x83, 0x51, 0x87, 0xac, 0x66, 0x79, 0x6f, 0x0e, 0xdc, 0x93, 0x07, 0x49, 0x87, 0xc3,
	0xa0, 0xc8, 0x1a, 0x94, 0x63, 0xa1, 0x8d, 0xb2, 0x8a, 0x3f, 0xe9, 0x56, 0xfc, 0x40, 0x7c, 0x58,
	0x1e, 0x6a, 0x3c, 0xcf, 0x48, 0x96, 0x67, 0x10, 0xcd, 0x84, 0x66, 0x92, 0x23, 0xa6, 0xec, 0x93,
	0xe5, 0xaf, 0xf5, 0x3d, 0x8b, 0x6f, 0x78, 0xdb, 0x58, 0xd2, 0x6a, 0x22, 0xe4, 0x29, 0xbc, 0x8c,
	0x48, 0x24, 0x4f, 0x3b, 0xbb, 0x47, 0xf1, 0x05, 0x71, 0x35, 0xf4, 0x38, 0xd9, 0xc6, 0x0d, 0xf2,
	0x0f, 0x08, 0xd7, 0x69, 0x07, 0xc6, 0xf5, 0x96, 0x16, 0xae, 0x41, 0x73, 0x41, 0xf3, 0x98, 0xfb,
	0xa3, 0x4d, 0x73, 0x81, 0xfb, 0x23, 0xf2, 0x5f, 0x88, 0x1a, 0x79, 0x75, 0x15, 0x7f, 0x2f, 0x74,
	0x5b, 0xf8, 0x9f, 0xc8, 0x12, 0xaf, 0x59, 0x55, 0x45, 0xc0, 0x4b, 0x78, 0xae, 0x3a, 0x69, 0x57,
	0xdc, 0x97, 0xcb, 0x5c, 0xe3, 0x6b, 0x88, 0x20, 0x67, 0x25, 0x6b, 0x43, 0x77, 0xa6, 0xff, 0x5b,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0x40, 0x6e, 0x59, 0x3b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (HelloService_ChatClient, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/pb.HelloService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (HelloService_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloService_serviceDesc.Streams[0], "/pb.HelloService/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceChatClient{stream}
	return x, nil
}

type HelloService_ChatClient interface {
	Send(*ClientStream) error
	Recv() (*ServerStream, error)
	grpc.ClientStream
}

type helloServiceChatClient struct {
	grpc.ClientStream
}

func (x *helloServiceChatClient) Send(m *ClientStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceChatClient) Recv() (*ServerStream, error) {
	m := new(ServerStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	Chat(HelloService_ChatServer) error
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedHelloServiceServer) Chat(srv HelloService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HelloService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).Chat(&helloServiceChatServer{stream})
}

type HelloService_ChatServer interface {
	Send(*ServerStream) error
	Recv() (*ClientStream, error)
	grpc.ServerStream
}

type helloServiceChatServer struct {
	grpc.ServerStream
}

func (x *helloServiceChatServer) Send(m *ServerStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceChatServer) Recv() (*ClientStream, error) {
	m := new(ClientStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloService_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _HelloService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hellostream.proto",
}
